# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://guoliu.github.io/ 
title: Guo Liu
email: liuguomailbox@gmail.com
author: Guo Liu
description: Guo Liu's project website on remote sensing, model optimization, climate feedbacks.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

  - title: github
    url: https://github.com/guoliu
  - title: linkedin
    url: https://www.linkedin.com/pub/guo-liu/a5/370/a73
  - title: Photography
    url: https://500px.com/Liu_Guo
