# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://guoliu.github.io/ 
title: Guo Liu's Personal Website
email: liuguomailbox@gmail.com
author: Guo Liu
description: Guo Liu's Personal Website on remote sensing, model optimization, photography.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

  - title: github
    url: https://github.com/guoliu
  - title: linkedin
    url: 
